backend:
  name: desertsofcacti/banana-for-scale

media_folder: static/assets
public_folder: static

collections:
  - name: banana-for-scale
    repo: git@github.com:desertsofcacti/banana-for-scale
    label: Entry
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
